name = "coastwatch-scraper"
main = "src/index.ts"
compatibility_date = "2024-03-14"
compatibility_flags = ["nodejs_compat"]

[triggers]
# Schedule cron triggers:
# every day at 3am
crons = [ "* 3 * * *" ]

# Bind a KV Namespace. Use KV as persistent storage for small key-value pairs.
# Docs: https://developers.cloudflare.com/workers/runtime-apis/kv
[[kv_namespaces]]
binding = "miles"
id = "c4fe5c8550854d63a55de2ba39fa4d00"
